
const KEY='escapeRoomReviewTracker.v200',MAX_UNDO=30,MAX_ARCHIVES=100;
const initial={goal:50,florence:{start:0,current:0,uncredited:0},employees:[
{id:'tj',name:'TJ',week:0,payroll:0,overall:0},{id:'izzy',name:'Izzy',week:0,payroll:0,overall:0},{id:'justin',name:'Justin',week:0,payroll:0,overall:0},{id:'craigin',name:'Craigin',week:0,payroll:0,overall:0},{id:'charlie',name:'Charlie',week:0,payroll:0,overall:0}],
locations:[{id:'stage',name:'Stage Road',start:0,current:0,goal:50},{id:'south',name:'South Main',start:0,current:0,goal:50},{id:'east',name:'East Memphis',start:0,current:0,goal:50},{id:'amuse',name:'Amuse Adventure Museum',start:0,current:0,goal:50},{id:'gnl',name:'Game Nite Lounge',start:0,current:0,goal:50}],history:[],weekArchives:[],payrollArchives:[]};
let state=load(),undo=[];
const $=id=>document.getElementById(id),clone=v=>JSON.parse(JSON.stringify(v)),uid=p=>`${p}_${Math.random().toString(36).slice(2,9)}${Date.now().toString(36).slice(-4)}`;
function load(){try{return {...clone(initial),...JSON.parse(localStorage.getItem(KEY))}}catch{return clone(initial)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));$('saveStatus').textContent='Saved locally • '+new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});render()}
function log(type,description){const d=new Date();state.history.unshift({date:d.toLocaleDateString(),time:d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}),type,description});state.history=state.history.slice(0,1000)}
function before(label){undo.push({label,state:clone(state)});if(undo.length>MAX_UNDO)undo.shift()}
function commit(label,type,description,fn){before(label);fn();log(type,description);save()}
function gained(a,b){return Math.max(0,+b-+a)}function pct(n,g){return Math.min(100,Math.round(+n/Math.max(1,+g)*100))}
function employee(id){return state.employees.find(x=>x.id===id)}function location(id){return state.locations.find(x=>x.id===id)}
function sync(){state.florence.current=+state.florence.start+state.employees.reduce((n,e)=>n+(+e.week),0)+(+state.florence.uncredited)}
function setView(v){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===v));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===v))}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>setView(b.dataset.view));
function render(){sync();dashboard();employees();locations();history();$('undoBtn').disabled=!undo.length;$('undoBtn').textContent=undo.length?'↶ Undo: '+undo.at(-1).label:'↶ Undo'}
function dashboard(){
 const fg=gained(state.florence.start,state.florence.current);$('flGained').textContent=fg;$('flGoal').textContent=state.goal;$('flStart').textContent=state.florence.start;$('flCurrent').textContent=state.florence.current;$('flProgress').style.width=pct(fg,state.goal)+'%';$('uncredited').textContent=$('uncreditedQuick').textContent=state.florence.uncredited;$('goalInput').value=state.goal;
 const es=[...state.employees].sort((a,b)=>b.week-a.week||a.name.localeCompare(b.name)),el=es[0];$('weeklyLeader').textContent=el&&el.week?el.name:'—';$('weeklyLeaderSub').textContent=el&&el.week?`${el.week} review${el.week===1?'':'s'} this week`:'No credited reviews yet.';
 const ls=[{name:'Florence',start:state.florence.start,current:state.florence.current,goal:state.goal},...state.locations].map(l=>({...l,gained:gained(l.start,l.current)})).sort((a,b)=>b.gained-a.gained||a.name.localeCompare(b.name));$('locationLeader').textContent=ls[0].gained?ls[0].name:'—';$('locationLeaderSub').textContent=ls[0].gained?`+${ls[0].gained} reviews this week`:'Waiting for the race to begin.';
 $('employeeLeaderboard').innerHTML=es.map((e,i)=>`<div class="leader"><div class="rank">${i+1}</div><div class="name">${e.name}</div><div><div class="ml">Weekly</div><div class="mv gain">${e.week}</div></div><div><div class="ml">Payroll</div><div class="mv">${e.payroll}</div></div><div class="last"><div class="ml">Overall</div><div class="mv">${e.overall}</div></div></div>`).join('');
 $('locationLeaderboard').innerHTML=ls.map((l,i)=>`<div class="leader"><div class="rank">${i+1}</div><div class="name">${l.name}</div><div><div class="ml">Gained</div><div class="mv gain">+${l.gained}</div></div><div><div class="ml">Current</div><div class="mv">${l.current}</div></div><div class="last"><div class="ml">Goal</div><div class="mv">${l.goal}</div></div></div>`).join('');
}
function employees(){
 $('employeeCards').innerHTML=state.employees.map(e=>`<article class="card"><h3>${e.name}</h3><div class="counts"><div class="count"><span>Week</span><strong>${e.week}</strong></div><div class="count"><span>Payroll</span><strong>${e.payroll}</strong></div><div class="count"><span>Overall</span><strong>${e.overall}</strong></div></div><div class="card-actions"><button class="round minus eminus" data-id="${e.id}">−</button><button class="round plus eplus" data-id="${e.id}">+</button><button class="btn secondary small eedit" data-id="${e.id}">Edit</button></div></article>`).join('');
 document.querySelectorAll('.eplus').forEach(b=>b.onclick=()=>adjustEmployee(b.dataset.id,1));document.querySelectorAll('.eminus').forEach(b=>b.onclick=()=>adjustEmployee(b.dataset.id,-1));document.querySelectorAll('.eedit').forEach(b=>b.onclick=()=>openEmployee(b.dataset.id));
}
function adjustEmployee(id,d){const e=employee(id);if(!e||d<0&&(e.week<=0||e.payroll<=0||e.overall<=0))return;commit(`${d>0?'+1':'-1'} ${e.name}`,'Employee Review',`${d>0?'+1':'-1'} review for ${e.name}`,()=>{e.week+=d;e.payroll+=d;e.overall+=d;sync()})}
function openEmployee(id=''){const e=id?employee(id):null;$('employeeDialogTitle').textContent=e?'Edit Employee':'Add Employee';$('employeeId').value=e?.id||'';$('employeeName').value=e?.name||'';$('employeeWeek').value=e?.week??0;$('employeePayroll').value=e?.payroll??0;$('employeeOverall').value=e?.overall??0;$('employeeDialog').showModal()}
$('addEmployeeBtn').onclick=()=>openEmployee();$('saveEmployeeBtn').onclick=()=>{const id=$('employeeId').value||uid('emp'),name=$('employeeName').value.trim();if(!name)return;const x={id,name,week:Math.max(0,+$('employeeWeek').value||0),payroll:Math.max(0,+$('employeePayroll').value||0),overall:Math.max(0,+$('employeeOverall').value||0)},i=state.employees.findIndex(e=>e.id===id);before(i>=0?'Edit '+name:'Add '+name);if(i>=0)state.employees[i]=x;else state.employees.push(x);log('Employee Edit',i>=0?`Edited totals for ${name}`:`Added employee ${name}`);$('employeeDialog').close();save()};
function locations(){
 $('locationCards').innerHTML=state.locations.map(l=>{const g=gained(l.start,l.current);return `<article class="card"><h3>${l.name}</h3><div class="counts"><div class="count"><span>Started</span><strong>${l.start}</strong></div><div class="count"><span>Current</span><strong>${l.current}</strong></div><div class="count"><span>Gained</span><strong class="gain">+${g}</strong></div></div><div class="loc-progress"><div class="progress"><i style="width:${pct(g,l.goal)}%"></i></div><div class="loc-sub"><span>${g} / ${l.goal}</span><span>${pct(g,l.goal)}%</span></div></div><div class="card-actions"><button class="round minus lminus" data-id="${l.id}">−</button><button class="round plus lplus" data-id="${l.id}">+</button><button class="btn secondary small ledit" data-id="${l.id}">Edit Totals</button></div></article>`}).join('');
 document.querySelectorAll('.lplus').forEach(b=>b.onclick=()=>adjustLocation(b.dataset.id,1));document.querySelectorAll('.lminus').forEach(b=>b.onclick=()=>adjustLocation(b.dataset.id,-1));document.querySelectorAll('.ledit').forEach(b=>b.onclick=()=>openLocation(b.dataset.id));
}
function adjustLocation(id,d){const l=location(id);if(!l||d<0&&l.current<=0)return;commit(`${d>0?'+1':'-1'} ${l.name}`,'Location Review',`${d>0?'+1':'-1'} ${l.name} review`,()=>l.current=Math.max(0,+l.current+d))}
function openLocation(id=''){const l=id?location(id):null;$('locationDialogTitle').textContent=l?'Edit Location':'Add Location';$('locationId').value=l?.id||'';$('locationName').value=l?.name||'';$('locationStart').value=l?.start??0;$('locationCurrent').value=l?.current??0;$('locationGoal').value=l?.goal??state.goal;$('locationDialog').showModal()}
$('addLocationBtn').onclick=()=>openLocation();$('saveLocationBtn').onclick=()=>{const id=$('locationId').value||uid('loc'),name=$('locationName').value.trim();if(!name)return;const x={id,name,start:Math.max(0,+$('locationStart').value||0),current:Math.max(0,+$('locationCurrent').value||0),goal:Math.max(1,+$('locationGoal').value||state.goal)},i=state.locations.findIndex(l=>l.id===id);before(i>=0?'Edit '+name:'Add '+name);if(i>=0)state.locations[i]=x;else state.locations.push(x);log('Location Edit',i>=0?`Edited totals for ${name}`:`Added location ${name}`);$('locationDialog').close();save()};
function uncredited(d){if(d<0&&state.florence.uncredited<=0)return;commit(`${d>0?'+1':'-1'} uncredited`,'Florence Review',`${d>0?'+1':'-1'} uncredited Florence review`,()=>state.florence.uncredited=Math.max(0,+state.florence.uncredited+d))}
$('uncreditedPlus').onclick=()=>uncredited(1);$('uncreditedMinus').onclick=()=>uncredited(-1);$('saveGoalBtn').onclick=()=>{const g=Math.max(1,+$('goalInput').value||50);commit('Change goal','Goal Change',`Changed goal from ${state.goal} to ${g}`,()=>state.goal=g)};
$('reconcileBtn').onclick=()=>{$('reconcileTotal').value=state.florence.current;$('reconcileDialog').showModal()};$('confirmReconcileBtn').onclick=()=>{const actual=Math.max(0,+$('reconcileTotal').value||0),cur=state.florence.current;if(actual<cur)return alert('Google total is lower than the tracker. Use minus/edit controls instead.');const diff=actual-cur;if(diff)commit('Reconcile Florence','Reconcile',`Reconciled Florence to ${actual}; added ${diff} uncredited`,()=>state.florence.uncredited+=diff);$('reconcileDialog').close()};
function newWeek(){if(!confirm('Start a new week? Weekly employee totals clear. Payroll and overall totals stay.'))return;commit('Weekly reset','Weekly Reset','Started a new review week',()=>{state.weekArchives.unshift({date:new Date().toISOString(),florence:{start:state.florence.start,end:state.florence.current,gained:gained(state.florence.start,state.florence.current)},employees:clone(state.employees.map(e=>({name:e.name,week:e.week}))),locations:clone(state.locations.map(l=>({name:l.name,start:l.start,end:l.current,gained:gained(l.start,l.current)})))});state.weekArchives=state.weekArchives.slice(0,MAX_ARCHIVES);state.florence.start=state.florence.current;state.florence.uncredited=0;state.employees.forEach(e=>e.week=0);state.locations.forEach(l=>l.start=l.current)})}
$('startWeekBtn').onclick=newWeek;$('newWeekTopBtn').onclick=newWeek;$('clearPayrollBtn').onclick=()=>{if(!confirm('Clear payroll totals only? Weekly and overall totals stay.'))return;commit('Payroll reset','Payroll Reset','Cleared employee payroll totals',()=>{state.payrollArchives.unshift({date:new Date().toISOString(),employees:clone(state.employees.map(e=>({name:e.name,payroll:e.payroll})))});state.payrollArchives=state.payrollArchives.slice(0,MAX_ARCHIVES);state.employees.forEach(e=>e.payroll=0)})};
$('undoBtn').onclick=()=>{const u=undo.pop();if(!u)return;state=u.state;log('Undo','Undid: '+u.label);save()};
function history(){$('changeHistory').innerHTML=state.history.length?state.history.map(h=>`<div class="hist"><div class="time">${h.date}<br>${h.time}</div><div class="type">${h.type}</div><div>${h.description}</div></div>`).join(''):'<div class="empty">No changes yet.</div>';$('weekArchives').innerHTML=state.weekArchives.length?state.weekArchives.map(w=>`<div class="archive"><strong>${new Date(w.date).toLocaleDateString()} • Florence +${w.florence.gained}</strong><span>${w.employees.map(e=>`${e.name}: ${e.week}`).join(' • ')}</span><span>${w.locations.map(l=>`${l.name}: +${l.gained}`).join(' • ')}</span></div>`).join(''):'<div class="empty">No weekly archives yet.</div>';$('payrollArchives').innerHTML=state.payrollArchives.length?state.payrollArchives.map(p=>`<div class="archive"><strong>${new Date(p.date).toLocaleDateString()}</strong><span>${p.employees.map(e=>`${e.name}: ${e.payroll}`).join(' • ')}</span></div>`).join(''):'<div class="empty">No payroll archives yet.</div>'}
function dl(name,text,type){const b=new Blob([text],{type}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u)}
$('exportCsvBtn').onclick=()=>{const rows=[['Date','Time','Type','Description'],...[...state.history].reverse().map(h=>[h.date,h.time,h.type,h.description])],csv=rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\\r\\n');dl('review-history.csv',csv,'text/csv');log('Export','Exported history CSV');save()};
$('backupBtn').onclick=()=>{dl('review-tracker-backup.json',JSON.stringify(state,null,2),'application/json');log('Backup','Exported data backup');save()};
$('restoreInput').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const x=JSON.parse(await f.text());if(!x.employees||!x.locations||!x.florence)throw Error('Not a valid tracker backup.');if(confirm('Replace current tracker data with this backup?')){before('Restore backup');state={...clone(initial),...x};log('Restore','Restored backup');save()}}catch(err){alert(err.message)}e.target.value=''};
$('resetAllBtn').onclick=()=>{if(confirm('Reset EVERYTHING?')&&confirm('Really reset all totals, history, employees, and archives?')){before('Reset everything');state=clone(initial);log('Reset','Reset all tracker data');save()}};
render();
